title = 'Hacklab UCM'
baseURL = 'https://docura.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false

theme = 'docura'


[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'
  material = 'materials'
